version: 2
jobs:
 build:
   machine: true
   steps:
    - checkout

    - run: wget -O /tmp/terraform0.12.21.zip https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip 

    - run: unzip -j /tmp/terraform0.12.21.zip && mv /tmp/terraform /usr/local/bin/terraform

    - run: ./terraform init test

    - run: ./terraform apply -auto-approve test
