version: 2
jobs:
 build:
   machine: true
   steps:
    - checkout

    - run: wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip 

    - run: sudo unzip -d /tmp/terraform /tmp/terraform.zip && sudo mv /tmp/terraform/terraform /usr/local/bin/terraform 

    - run: /usr/local/bin/terraform init test

    - run: /usr/local/bin/terraform apply -auto-approve test
