version: 2
jobs:
 build:
   machine: true
   steps:
    - checkout

    - run: wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip 

    - run: sudo unzip -d /usr/local/bin/terraform /tmp/terraform.zip 

    - run: ./terraform init test

    - run: ./terraform apply -auto-approve test
