version: 2
jobs:
 build:
   machine: true
   steps:
    - checkout
    - run: echo 0 >> .k3s_token

    - run: echo 0 >> id_rsa.pub

    - run: wget https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip 

    - run: unzip -j terraform_0.12.21_linux_amd64

    - run: ./terraform apply -auto-approve
