version: 2
jobs:
 build:
   machine: true
   steps:
    - checkout

    - run: wget https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip 

    - run: unzip -j terraform_0.12.21_linux_amd64

    - run: ./terraform init test

    - run: ./terraform apply -auto-approve test
